export const LOAD_TODOS_FROM_BACKEND_BEGIN = "LOAD_TODOS_FROM_BACKEND_BEGIN";
export const LOAD_TODOS_FROM_BACKEND_SUCCESS =
  "LOAD_TODOS_FROM_BACKEND_SUCCESS";
export const LOAD_TODOS_FROM_BACKEND_ERROR = "LOAD_TODOS_FROM_BACKEND_ERROR";

export const CREATE_A_TODO_BEGIN = "CREATE_A_TODO_BEGIN";
export const CREATE_A_TODO_SUCCESS = "CREATE_A_TODO_SUCCESS";
export const CREATE_A_TODO_ERROR = "CREATE_A_TODO_ERROR";

export const EDIT_THE_TODO_BEGIN = "EDIT_THE_TODO_BEGIN";
export const EDIT_THE_TODO_SUCCESS = "EDIT_THE_TODO_SUCCESS";
export const EDIT_THE_TODO_ERROR = "EDIT_THE_TODO_ERROR";

export const COMPLETE_THE_TODO_BEGIN = "COMPLETE_THE_TODO_BEGIN";
export const COMPLETE_THE_TODO_SUCCESS = "COMPLETE_THE_TODO_SUCCESS";
export const COMPLETE_THE_TODO_ERROR = "COMPLETE_THE_TODO_ERROR";

export const DELETE_THE_TODO_BEGIN = "DELETE_THE_TODO_BEGIN";
export const DELETE_THE_TODO_SUCCESS = "DELETE_THE_TODO_SUCCESS";
export const DELETE_THE_TODO_ERROR = "DELETE_THE_TODO_ERROR";

export const START_EDITING_TODO = "START_EDITING_TODO";

export const CHANGE_FORM_TITLE_INPUT_VALUE = "CHANGE_FORM_TITLE_INPUT_VALUE";

export const CHANGE_FORM_BODY_INPUT_VALUE = "CHANGE_FORM_BODY_INPUT_VALUE";

export const FINISH_EDIT = "FINISH_EDIT";

export const CLEAR_INPUTS = "CLEAR_INPUTS";
